services:

  web: # use alpine 3.22
    image: nginx:mainline-alpine3.22-slim
    container_name: nginx-proxy
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    restart: unless-stopped
    networks:
      - blog
    depends_on:
      - post-service
      - user-client

  post-service:
    build:
      context: ./blog-service
      dockerfile: Dockerfile
    container_name: post-api
    restart: unless-stopped    
    env_file:
      - ./blog-service/.env
    networks:
      - blog
    depends_on:
      postgres:
        condition: service_healthy

  postgres:
    image: postgres:18
    env_file:
      - ./blog-service/.env
    volumes:
      - pgdata_v2:/var/lib/postgresql/data

    ports:
      - "8090:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postuser -d postdb"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped
    networks:
      - blog
    
  user-client:
    build:
      context: ./blog-client
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_API_URL: http://post-service:8080
    container_name: user-client
    restart: unless-stopped
    networks:
      - blog
    environment:
      - NEXT_PUBLIC_API_URL=/api
    depends_on:
      - post-service


networks:
  blog:
    driver: bridge

volumes:
  pgdata_v2: